# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml

#################################################################################################
# define all the items that should appear in this environment



engines:
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------
  tk-desktop:
    apps:
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-screeningroom: '@launch_screeningroom'
    collapse_rules:
    - {button_label: $app, match: Launch $app, menu_label: None}
    debug_logging: false
    default_group: Studio
    groups:
    - matches: ['*Maya*', '*Nuke*', '*Photoshop*']
      name: Creative Tools
    - matches: ['*Hiero*']
      name: Editorial Tools
    - matches: ['*Fla*']
      name: Finishing Tools
    hook_launch_python: default
    location:
      version: v2.0.9
      type: app_store
      name: tk-desktop
    show_recents: true

  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles-launch-at-startup'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location:
      version: v0.5.3
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project:
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # Nuke
  # -------------------------------------------------
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location:
      version: v0.4.1
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
    bin_context_menu: []
    spreadsheet_context_menu: []
    timeline_context_menu: []
  #
  # -------------------------------------------------
  # Photoshop
  # -------------------------------------------------
  tk-photoshop:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    debug_logging: false
    location:
      name: tk-photoshop
      type: app_store
      version: v0.3.2

  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-screeningroom: '@launch_screeningroom'
    location:
      name: tk-shell
      type: app_store
      version: v0.4.1

#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-adminui_v0.x.x:
    location:
      name: tk-framework-adminui
      type: app_store
      version: v0.1.2
  tk-framework-login_v1.x.x:
    location:
      version: v1.2.1
      type: app_store
      name: tk-framework-login
  tk-framework-softimageqt_v1.0.1:
    location:
      name: tk-framework-softimageqt
      type: app_store
      version: v1.0.1
